///
/// This is an X-Macro File
/// 

#ifndef KDL_NODE_TYPE(name)
# error "KDL_NODE_TYPE must be defined"
#endif 


KDL_NODE_TYPE(UNTYPED)
KDL_NODE_TYPE(PROGRAM)
KDL_NODE_TYPE(RULE)
KDL_NODE_TYPE(PREDICATE)
KDL_NODE_TYPE(IDENTIFIER)
KDL_NODE_TYPE(LITERAL)
KDL_NODE_TYPE(BINARY_OP)
KDL_NODE_TYPE(UNARY_OP)
KDL_NODE_TYPE(STMT)
KDL_NODE_TYPE(DECL)
KDL_NODE_TYPE(BLOCK)

#undef KDL_NODE_TYPE