// THIS FILE WAS AUTOMATICALLY GENERATED BY KDL
// KDL is licensed under GPLv3.

#ifdef KSR_COMPILE_AS_DYNLIB
# ifndef KSR_API
#  if defined(_MSC_VER)
#   define KSR_API __declspec(dllexport)
#  elif defined(__GNUC__)
#   define KSR_API __attribute__((visibility("default")))
#  else
#    error "Unsupported compiler!"
#  endif
# endif
#else
# define KSR_API
#endif // KSR_COMPILE_AS_DYNLIB



#ifdef __cplusplus
extern "C"{
#endif // __cplusplus


#include <stdbool.h>

KSR_API bool kdl_rule_email_Ukraine_power_attack_content(const unsigned char*, unsigned int);

KSR_API bool kdl_rule_pony_malware(const unsigned char*, unsigned int);

KSR_API bool kdl_rule_EICAR(const unsigned char*, unsigned int);



#ifdef __cplusplus
}
#endif // __cplusplus
// End of auto-generated header file